export const themes = [
  {
    id: "default",
    name: "Default",
    description: "A clean and minimal base theme.",
    lightImage: "/themes/defaultLight.webp",
    darkImage: "/themes/defaultDark.webp",
    lightClass: "default",
    darkClass: "default dark",
  },
  {
    id: "sandsOfTime",
    name: "Sands of Time",
    description:
      "Warm golden hues and soft shadows evoking the desert sun and timeless serenity.",
    lightImage: "/themes/sandsOfTimeLight.webp",
    darkImage: "/themes/sandsOfTimeDark.webp",
    lightClass: "sandsOfTime",
    darkClass: "sandsOfTime dark",
  },
  {
    id: "notebook",
    name: "Obsidian Draft",
    description:
      "A monochrome theme for creators and coders — minimal, structured, and effortlessly modern.",
    lightImage: "/themes/notebookLight.webp",
    darkImage: "/themes/notebookDark.webp",
    lightClass: "notebook",
    darkClass: "notebook dark",
  },
  {
    id: "bubblegumPop",
    name: "Bubblegum Pop",
    description: "A candy-colored UI inspired by bubblegum dreams.",
    lightImage: "/themes/bubblegumLight.webp",
    darkImage: "/themes/bubblegumDark.webp",
    lightClass: "bubblegumPop",
    darkClass: "bubblegumPop dark",
  },
  {
    id: "greenPower",
    name: "Green Power",
    description: "A sleek, vibrant UI theme powered by energizing greens.",
    lightImage: "/themes/greenPowerLight.webp",
    darkImage: "/themes/greenPowerDark.webp",
    lightClass: "greenPower",
    darkClass: "greenPower dark",
  },
  {
    id: "doom",
    name: "Neon Inferno",
    description: "A high-energy theme with bold contrasts.",
    lightImage: "/themes/doomLight.webp",
    darkImage: "/themes/doomDark.webp",
    lightClass: "doom",
    darkClass: "doom dark",
  },
  {
    id: "boldTech",
    name: "Bold Tech",
    description: "A fresh and energetic UI with tech-forward vibes.",
    lightImage: "/themes/techLight.webp",
    darkImage: "/themes/techDark.webp",
    lightClass: "boldTech",
    darkClass: "boldTech dark",
  },
  {
    id: "pastel",
    name: "Pastel",
    description: "A soft and calming palette with subtle pastel tones.",
    lightImage: "/themes/pastelLight.webp",
    darkImage: "/themes/pastelDark.webp",
    lightClass: "pastel",
    darkClass: "pastel dark",
  },
];
